In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
os.chdir('C:\\Post Graduate Course in Data Analytics\\MACHINE LEARNING\\LR & DT')

In [3]:
df_book = pd.read_csv('BookingDetails.csv')
df_book.head()

hotel  is_canceled  arrival_date_year arrival_date_month  \
0  City Hotel            0               2017                May   
1  City Hotel            0               2017              April   
2  City Hotel            1               2016               June   
3  City Hotel            0               2016             August   
4  City Hotel            0               2017             August   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                          5                        0                     1   
1                          7                        0                     1   
2                         17                        0                     2   
3                         16                        0                     3   
4                         21                        1                     2   

   adults  children  babies  ... is_repeated_guest previous_cancellations  \
0       2         0       0  ...                 0                      0   
1       1         0       0  ...                 0                      0   
2       2         0       0  ...                 0                      0   
3       2         0       0  ...                 0                      0   
4       2         1       0  ...                 0                      0   

  previous_bookings_not_canceled  reserved_room_type  assigned_room_type  \
0                              0                   A                   A   
1                              0                   A                   A   
2                              0                   A                   A   
3                              0                   A                   A   
4                              0                   G                   G   

   deposit_type days_in_waiting_list    customer_type  \
0    No Deposit                    0  Transient-Party   
1    No Deposit                    0        Transient   
2    Non Refund                    0        Transient   
3    No Deposit                    0        Transient   
4    No Deposit                    0        Transient   

  required_car_parking_spaces  reservation_status  
0                           0           Check-Out  
1                           0           Check-Out  
2                           0            Canceled  
3                           0           Check-Out  
4                           0           Check-Out  

[5 rows x 23 columns]

In [4]:
df_book.is_canceled.value_counts()

0    3139
1    1861
Name: is_canceled, dtype: int64

In [5]:
df_book.shape

(5000, 23)

In [6]:
categorical=df_book.select_dtypes('category')
numerical=df_book.select_dtypes(np.number)
print(categorical.columns)
print(numerical.columns)

Index([], dtype='object')
Index(['is_canceled', 'arrival_date_year', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'days_in_waiting_list',
       'required_car_parking_spaces'],
      dtype='object')


In [7]:
df_book.isnull().sum()

hotel                             0
is_canceled                       0
arrival_date_year                 0
arrival_date_month                0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
required_car_parking_spaces       0
reservation_status                0
dtype: int64

In [8]:
df_book.describe()

is_canceled  arrival_date_year  arrival_date_day_of_month  \
count   5000.00000        5000.000000                5000.000000   
mean       0.37220        2016.155400                  15.750400   
std        0.48344           0.707496                   8.697174   
min        0.00000        2015.000000                   1.000000   
25%        0.00000        2016.000000                   8.000000   
50%        0.00000        2016.000000                  16.000000   
75%        1.00000        2017.000000                  23.000000   
max        1.00000        2017.000000                  31.000000   

       stays_in_weekend_nights  stays_in_week_nights       adults  \
count               5000.00000           5000.000000  5000.000000   
mean                   0.91880              2.501200     1.856000   
std                    0.97324              1.839857     0.482193   
min                    0.00000              0.000000     0.000000   
25%                    0.00000              1.000000     2.000000   
50%                    1.00000              2.000000     2.000000   
75%                    2.00000              3.000000     2.000000   
max                    8.00000             22.000000     4.000000   

          children       babies  is_repeated_guest  previous_cancellations  \
count  5000.000000  5000.000000        5000.000000             5000.000000   
mean      0.111200     0.007000           0.029600                0.085400   
std       0.408005     0.085747           0.169498                0.807117   
min       0.000000     0.000000           0.000000                0.000000   
25%       0.000000     0.000000           0.000000                0.000000   
50%       0.000000     0.000000           0.000000                0.000000   
75%       0.000000     0.000000           0.000000                0.000000   
max       3.000000     2.000000           1.000000               25.000000   

       previous_bookings_not_canceled  days_in_waiting_list  \
count                     5000.000000           5000.000000   
mean                         0.127200              2.388600   
std                          1.544246             16.735471   
min                          0.000000              0.000000   
25%                          0.000000              0.000000   
50%                          0.000000              0.000000   
75%                          0.000000              0.000000   
max                         69.000000            330.000000   

       required_car_parking_spaces  
count                  5000.000000  
mean                      0.060800  
std                       0.243958  
min                       0.000000  
25%                       0.000000  
50%                       0.000000  
75%                       0.000000  
max                       3.000000

In [9]:
df_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   hotel                           5000 non-null   object
 1   is_canceled                     5000 non-null   int64 
 2   arrival_date_year               5000 non-null   int64 
 3   arrival_date_month              5000 non-null   object
 4   arrival_date_day_of_month       5000 non-null   int64 
 5   stays_in_weekend_nights         5000 non-null   int64 
 6   stays_in_week_nights            5000 non-null   int64 
 7   adults                          5000 non-null   int64 
 8   children                        5000 non-null   int64 
 9   babies                          5000 non-null   int64 
 10  meal                            5000 non-null   object
 11  country                         5000 non-null   object
 12  distribution_channel            5000 non-null   

In [17]:
cat=df_book.select_dtypes(include='object')
cat.columns

Index(['hotel', 'meal', 'country', 'distribution_channel',
       'reserved_room_type', 'assigned_room_type', 'deposit_type',
       'customer_type', 'reservation_status'],
      dtype='object')

In [12]:
month={'January':1,'February':2,'March':3,'April':4,'May':5,'June':6,'July':7,'August':8,'September':9,'October':10,'November':11,'December':12}

In [14]:
df_book['arrival_date_month'].replace(month.keys(),month.values(),inplace=True)

In [16]:
df_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   hotel                           5000 non-null   object
 1   is_canceled                     5000 non-null   int64 
 2   arrival_date_year               5000 non-null   int64 
 3   arrival_date_month              5000 non-null   int64 
 4   arrival_date_day_of_month       5000 non-null   int64 
 5   stays_in_weekend_nights         5000 non-null   int64 
 6   stays_in_week_nights            5000 non-null   int64 
 7   adults                          5000 non-null   int64 
 8   children                        5000 non-null   int64 
 9   babies                          5000 non-null   int64 
 10  meal                            5000 non-null   object
 11  country                         5000 non-null   object
 12  distribution_channel            5000 non-null   

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for i in cat.columns:
    df_book[i]=le.fit_transform(df_book[i])

In [21]:
df_book.head()

hotel  is_canceled  arrival_date_year  arrival_date_month  \
0      0            0               2017                   5   
1      0            0               2017                   4   
2      0            1               2016                   6   
3      0            0               2016                   8   
4      0            0               2017                   8   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                          5                        0                     1   
1                          7                        0                     1   
2                         17                        0                     2   
3                         16                        0                     3   
4                         21                        1                     2   

   adults  children  babies  ...  is_repeated_guest  previous_cancellations  \
0       2         0       0  ...                  0                       0   
1       1         0       0  ...                  0                       0   
2       2         0       0  ...                  0                       0   
3       2         0       0  ...                  0                       0   
4       2         1       0  ...                  0                       0   

   previous_bookings_not_canceled  reserved_room_type  assigned_room_type  \
0                               0                   0                   0   
1                               0                   0                   0   
2                               0                   0                   0   
3                               0                   0                   0   
4                               0                   6                   6   

   deposit_type  days_in_waiting_list  customer_type  \
0             0                     0              3   
1             0                     0              2   
2             1                     0              2   
3             0                     0              2   
4             0                     0              2   

   required_car_parking_spaces  reservation_status  
0                            0                   1  
1                            0                   1  
2                            0                   0  
3                            0                   1  
4                            0                   1  

[5 rows x 23 columns]

In [23]:
from sklearn.model_selection import train_test_split

In [25]:
x=df_book.drop('is_canceled',axis=1)
print(x.shape)
y=df_book['is_canceled']
print(y.shape)

(5000, 22)
(5000,)


In [26]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=123)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(4000, 22)
(1000, 22)
(4000,)
(1000,)


In [27]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression(solver='liblinear')
model1.fit(xtrain,ytrain)

print(model1.coef_)
print(model1.intercept_)

[[-5.48251171e-01  9.91999065e-04  1.61042016e-02  1.10261953e-04
   9.94530644e-02  9.32123062e-02 -2.65906794e-01  8.32906595e-02
  -9.83468806e-02 -4.07569889e-02  2.33895072e-02  1.82216270e-01
  -8.78942816e-02  6.39971909e-01 -9.89871091e-02  9.30713447e-02
  -7.80672594e-02  1.31594975e+00 -7.89015249e-03 -1.73750992e-01
  -8.59409418e-01 -6.06881578e+00]]
[-0.000764]


In [28]:
ypred=model1.predict(xtest)
ypred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,

In [30]:
from sklearn.metrics import classification_report,confusion_matrix

In [31]:
confusion_matrix(ytest,ypred)

array([[632,   2],
       [  8, 358]], dtype=int64)

In [32]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       634
           1       0.99      0.98      0.99       366

    accuracy                           0.99      1000
   macro avg       0.99      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000



In [34]:
model2=LogisticRegression(solver='liblinear')
model2.fit(x,y)

print(model2.coef_)
print(model2.intercept_)

[[-4.98617482e-01  1.11179667e-03  1.63493821e-02  2.54869991e-03
   9.79830980e-02  7.48715289e-02 -2.51441519e-01  7.49109926e-02
  -9.24641576e-02 -7.97932772e-02  2.25494769e-02  1.75401481e-01
  -9.87944448e-02  3.23149617e-01 -7.73317637e-02  1.49399687e-01
  -1.21533643e-01  1.39566692e+00 -7.41343709e-03 -2.37647677e-01
  -8.86016865e-01 -6.19482194e+00]]
[-0.00063653]


In [37]:
ypred2=model2.predict(x)
ypred2

array([0, 0, 1, ..., 0, 1, 0], dtype=int64)

In [38]:
confusion_matrix(y,ypred2)

array([[3139,    0],
       [  55, 1806]], dtype=int64)

In [39]:
print(classification_report(y,ypred2))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3139
           1       1.00      0.97      0.99      1861

    accuracy                           0.99      5000
   macro avg       0.99      0.99      0.99      5000
weighted avg       0.99      0.99      0.99      5000



In [40]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [41]:
xtrain_sc=sc.fit_transform(xtrain)
xtest_sc=sc.fit_transform(xtest)

In [42]:
model3=LogisticRegression(solver='liblinear')
model3.fit(xtrain_sc,ytrain)

LogisticRegression(solver='liblinear')

In [43]:
ypred3=model3.predict(xtest_sc)
ypred3

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,

In [44]:
confusion_matrix(ytest,ypred3)

array([[632,   2],
       [  8, 358]], dtype=int64)

In [45]:
print(classification_report(ytest,ypred3))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       634
           1       0.99      0.98      0.99       366

    accuracy                           0.99      1000
   macro avg       0.99      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000

