In [1]:
!pip install --user tensorflow

In [2]:
from tensorflow import keras
from keras.datasets import mnist
from keras import models 
from keras import layers


In [3]:
from tensorflow.keras.utils import to_categorical

In [4]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [5]:
#https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz

In [6]:
train_images.shape

(60000, 28, 28)

In [7]:
len(train_labels)

60000

In [8]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
test_images.shape

(10000, 28, 28)

In [10]:
len(test_labels)

10000

In [11]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

#the network architecture

In [12]:
network = models.Sequential()

In [13]:
network.add(layers.Dense(512, activation='relu',input_shape=(28 * 28,)))


# relu - rectified linear unit f(x) = max(0,x) 
# the function returns 0 if it receives any negative input , but for any positive value x, it returns thet the value back.
# thus it gives an output that has a range from 0 to infinity

In [14]:
network.add(layers.Dense(10,activation='softmax'))

# softmax layer , which means it will returns an array of 10 probability scores

%% The compilation step

In [15]:
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

# Loss function - To measure its performance on training dataset 
# optimizer - The machanism through which the network will update itself based on the data it sees and its loss function 
# metrics - accuracy i.e ( the fraction of the images that were correctly classified )

#--Re-shaping & scaling, train_data 

In [16]:
train_images.shape

(60000, 28, 28)

In [17]:
train_images = train_images.reshape((60000, 28 * 28))

In [18]:
train_images.shape

(60000, 784)

# scaling the data set

In [19]:
train_images

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [20]:
train_images = train_images.astype('float32') / 255

In [21]:
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Re-shaping & scaling , test_data

In [22]:
test_images = test_images.reshape((10000, 28 * 28)) # reshaping

In [23]:
test_images

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [24]:
test_images = test_images.astype('float32') / 255 # scaling

In [25]:
test_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# train labels as categories

In [26]:
train_labels = to_categorical(train_labels)

In [27]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

# test labels as categories

In [28]:
test_labels = to_categorical(test_labels)

In [29]:
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# run the model on train data

In [30]:
network.fit(train_images,train_labels, epochs=5,batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 14ms/step - loss: 0.2537 - accuracy: 0.9267
Epoch 2/5
469/469 [==============================] - 7s 14ms/step - loss: 0.1034 - accuracy: 0.9696
Epoch 3/5
469/469 [==============================] - 7s 14ms/step - loss: 0.0676 - accuracy: 0.9799
Epoch 4/5
469/469 [==============================] - 7s 14ms/step - loss: 0.0489 - accuracy: 0.9857
Epoch 5/5
469/469 [==============================] - 7s 14ms/step - loss: 0.0368 - accuracy: 0.9886


# test data performance

In [31]:
test_loss,test_acc = network.evaluate(test_images,test_labels)

313/313 [==============================] - 2s 4ms/step - loss: 0.0703 - accuracy: 0.9790: 0s - loss: 0.0840 - ac


In [32]:
print('test_acc:',test_acc)

test_acc: 0.9789999723434448
