In [1]:
!pip install tensorflow

In [3]:
from tensorflow import keras
from keras.datasets import mnist
from keras import models
from keras import layers
from tensorflow.keras.utils import to_categorical

In [4]:
#mnist as set of 60000 training images,
#each 28*28 pixel assembled by the National 
#Institute of Standards and technology the(NIST in MNIST)in 1980s.

In [15]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

In [7]:
#''''''the above images are encoded as numpy arrays, and the
# labels are an array of digits, rangingfrom 0 to 9 .The images 
# and labels have a one-to-one correspondance''''''

In [8]:
#train_images

In [16]:
train_images.shape

(60000, 28, 28)

In [17]:
train_images #array of uint8(60000,28,28)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [18]:
#train_labels
len(train_labels)

60000

In [19]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [13]:
#Test data,10000

In [20]:
test_images.shape

(10000, 28, 28)

In [21]:
len(test_labels)

10000

In [22]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [23]:
#THE NEURAL NETWORK

In [25]:
#the network architecture
from keras import models
from keras import layers

In [26]:
network=models.Sequential()

In [27]:
network.add(layers.Dense(512,activation='relu',input_shape=(28*28,)))

In [28]:
# "relu-rectified linear unit f(x)=max(0,x)
# the function returns 0 if it receives any negative input,
# but for any positive value x,it returns that value back.
# Thus it gives an output that has a range from 0 to infinity."

In [29]:
network.add(layers.Dense(10,activation="softmax"))

In [30]:
# "softmax layer,which means 
#it will return an array of 10 probability scores"

In [31]:
#THE COMPILATION STEP

In [33]:
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',
               metrics=['accuracy'])

In [34]:
#' loss function-To measure its performance on training dataset 
# optimizer-the mechanism through which the network will update
# itself based on the data it sees and its loss function
# metrics-Accuracy ie (the fraction of the images that were 
  #   correctly classified)'

In [35]:
#Re-shaping and scaling,train_data

In [36]:
#Preparing the image data
# "Before traiining ,we'll preprocess the data by reshaping it into 
# the shape the networkexpects and scaling it so that all values are 
# in the [0,1] interval."  

In [37]:
train_images.shape

(60000, 28, 28)

In [38]:
train_images=train_images.reshape((60000,28*28))

In [39]:
train_images.shape #28*28=784

(60000, 784)

In [40]:
#scaling the data

In [41]:
train_images=train_images.astype('float32')/255

In [42]:
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
#RE-SHAPING & SCALING ,TEST_DATA

In [43]:
test_images=test_images.reshape((10000,28*28))#reshaping

In [44]:
test_images=test_images.astype('float32')/255 #scaling

In [45]:
test_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
#train _labels as categories
#preparing the labels

In [ ]:
from keras.utils import to_categorical

In [46]:
train_labels=to_categorical(train_labels)

In [47]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [ ]:
# test_labels as categories

In [48]:
test_labels=to_categorical(test_labels)

In [49]:
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [50]:
#RUN THE MODEL ON TRAIN DATA

In [51]:
# fitting the model to its train data
network.fit(train_images,train_labels,epochs=5,batch_size=128)
#accuracy:0.9899 epoch5/5

Epoch 1/5
469/469 [==============================] - 5s 9ms/step - loss: 0.2570 - accuracy: 0.9246
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.1040 - accuracy: 0.9691
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0675 - accuracy: 0.9798
Epoch 4/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0487 - accuracy: 0.9847
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0372 - accuracy: 0.9890


In [52]:
#test data performance

In [53]:
test_loss,test_acc=network.evaluate(test_images,test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.0762 - accuracy: 0.9778


In [54]:
print('test_acc:',test_acc)#test_acc:0.9794999957084656

test_acc: 0.9778000116348267
